### ISSUE TITLE
Landing Page Development

### ISSUE THREAD

**Issue by liveBuildKenya** [SongaBiz/Songa#3]
Based on the landing page redesign we are requesting a redevelopment of the landing page.

**Comment by komenAnna** [comment]
Noted. Kindly share the Figma link of the designs.

**Comment by liveBuildKenya** [comment]
Here is the [link](https://www.figma.com/proto/hDMGpT1hUBDAALc1t1MWey/LANDING-UI?type=design&node-id=1-6&t=VXwfPJva5bscZolY-1&scaling=scale-down&page-id=0%3A1&mode=design)
