### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by liveBuildKenya** [SongaBiz/Songa#4]
Currently the repository does not have instructions on how to build project on development mode, as well as deploying to production.

Update the readme file to include: -

- [x] Procedure to clone the project
- [x] Prerequisite before building the project
- [x] Procedure to build and run the project on development mode
- [x] Procedure to build and run the project on production mode, the recommended way.

**Comment by komenAnna** [comment]
Received. Will update by COB today.
